# Generated by Django 4.2.7 on 2023-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='shortsummery',
            field=models.CharField(default='sds', max_length=500),
            preserve_default=False,
        ),
    ]
